version: "3.3"
services:
  front:
    build: front/
    container_name: front
    networks:
      - app-network
    depends_on:
      - httpd
      - api
  api:
    build: simple-api/
    container_name: api
    networks:
      - app-network
    depends_on:
      - db
    restart: always
  db:
    build: database/
    container_name: db
    networks:
      - app-network
    volumes:
      - data:/var/lib/postgresql/data
    restart: always
  httpd:
    build: httpserver/
    container_name: httpserver
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - api
    restart: always
volumes:
  data:
networks:
  app-network: