# tasks file for network

- name: Create back network
  docker_network:
    name: backend
    connected:
      - db
      - api

- name: Create front network
  docker_network:
    name: frontend
    connected:
      - api
      - httpserver
      - front
